# image thresholding

In [1]:
import cv2
import numpy

In [13]:
im1=cv2.imread("C:/Users/SN124/image/ben 10.jfif")

In [14]:
im1

array([[[ 72, 198, 186],
        [ 72, 198, 186],
        [ 71, 199, 187],
        ...,
        [ 63, 192, 161],
        [ 62, 191, 160],
        [ 62, 191, 160]],

       [[ 72, 198, 186],
        [ 72, 198, 186],
        [ 71, 199, 187],
        ...,
        [ 63, 192, 161],
        [ 62, 191, 160],
        [ 62, 191, 160]],

       [[ 72, 199, 184],
        [ 72, 199, 184],
        [ 71, 200, 185],
        ...,
        [ 63, 192, 161],
        [ 62, 191, 160],
        [ 62, 191, 160]],

       ...,

       [[  6,   0,   1],
        [  6,   0,   1],
        [  6,   0,   1],
        ...,
        [  6,   0,   1],
        [  6,   0,   1],
        [  6,   0,   1]],

       [[  6,   0,   1],
        [  6,   0,   1],
        [  6,   0,   1],
        ...,
        [  6,   0,   1],
        [  6,   0,   1],
        [  6,   0,   1]],

       [[  6,   0,   1],
        [  6,   0,   1],
        [  6,   0,   1],
        ...,
        [  6,   0,   1],
        [  6,   0,   1],
        [  6,   0,   1]]

In [16]:
cv2.imshow("im1",im1)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [17]:
ret,thers1=cv2.threshold(im1,83,100,cv2.THRESH_BINARY)
ret,thers2=cv2.threshold(im1,83,100,cv2.THRESH_BINARY_INV)
ret,thers3=cv2.threshold(im1,83,100,cv2.THRESH_TRUNC)
ret,thers4=cv2.threshold(im1,83,100,cv2.THRESH_TOZERO)
ret,thers5=cv2.threshold(im1,83,100,cv2.THRESH_TOZERO_INV)

In [19]:
thers1

array([[[  0, 100, 100],
        [  0, 100, 100],
        [  0, 100, 100],
        ...,
        [  0, 100, 100],
        [  0, 100, 100],
        [  0, 100, 100]],

       [[  0, 100, 100],
        [  0, 100, 100],
        [  0, 100, 100],
        ...,
        [  0, 100, 100],
        [  0, 100, 100],
        [  0, 100, 100]],

       [[  0, 100, 100],
        [  0, 100, 100],
        [  0, 100, 100],
        ...,
        [  0, 100, 100],
        [  0, 100, 100],
        [  0, 100, 100]],

       ...,

       [[  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        ...,
        [  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0]],

       [[  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        ...,
        [  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0]],

       [[  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        ...,
        [  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0]]

In [21]:
thers2

array([[[100,   0,   0],
        [100,   0,   0],
        [100,   0,   0],
        ...,
        [100,   0,   0],
        [100,   0,   0],
        [100,   0,   0]],

       [[100,   0,   0],
        [100,   0,   0],
        [100,   0,   0],
        ...,
        [100,   0,   0],
        [100,   0,   0],
        [100,   0,   0]],

       [[100,   0,   0],
        [100,   0,   0],
        [100,   0,   0],
        ...,
        [100,   0,   0],
        [100,   0,   0],
        [100,   0,   0]],

       ...,

       [[100, 100, 100],
        [100, 100, 100],
        [100, 100, 100],
        ...,
        [100, 100, 100],
        [100, 100, 100],
        [100, 100, 100]],

       [[100, 100, 100],
        [100, 100, 100],
        [100, 100, 100],
        ...,
        [100, 100, 100],
        [100, 100, 100],
        [100, 100, 100]],

       [[100, 100, 100],
        [100, 100, 100],
        [100, 100, 100],
        ...,
        [100, 100, 100],
        [100, 100, 100],
        [100, 100, 100]]

In [22]:
thers3

array([[[72, 83, 83],
        [72, 83, 83],
        [71, 83, 83],
        ...,
        [63, 83, 83],
        [62, 83, 83],
        [62, 83, 83]],

       [[72, 83, 83],
        [72, 83, 83],
        [71, 83, 83],
        ...,
        [63, 83, 83],
        [62, 83, 83],
        [62, 83, 83]],

       [[72, 83, 83],
        [72, 83, 83],
        [71, 83, 83],
        ...,
        [63, 83, 83],
        [62, 83, 83],
        [62, 83, 83]],

       ...,

       [[ 6,  0,  1],
        [ 6,  0,  1],
        [ 6,  0,  1],
        ...,
        [ 6,  0,  1],
        [ 6,  0,  1],
        [ 6,  0,  1]],

       [[ 6,  0,  1],
        [ 6,  0,  1],
        [ 6,  0,  1],
        ...,
        [ 6,  0,  1],
        [ 6,  0,  1],
        [ 6,  0,  1]],

       [[ 6,  0,  1],
        [ 6,  0,  1],
        [ 6,  0,  1],
        ...,
        [ 6,  0,  1],
        [ 6,  0,  1],
        [ 6,  0,  1]]], dtype=uint8)

In [23]:
thers4

array([[[  0, 198, 186],
        [  0, 198, 186],
        [  0, 199, 187],
        ...,
        [  0, 192, 161],
        [  0, 191, 160],
        [  0, 191, 160]],

       [[  0, 198, 186],
        [  0, 198, 186],
        [  0, 199, 187],
        ...,
        [  0, 192, 161],
        [  0, 191, 160],
        [  0, 191, 160]],

       [[  0, 199, 184],
        [  0, 199, 184],
        [  0, 200, 185],
        ...,
        [  0, 192, 161],
        [  0, 191, 160],
        [  0, 191, 160]],

       ...,

       [[  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        ...,
        [  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0]],

       [[  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        ...,
        [  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0]],

       [[  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        ...,
        [  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0]]

In [24]:
thers5

array([[[72,  0,  0],
        [72,  0,  0],
        [71,  0,  0],
        ...,
        [63,  0,  0],
        [62,  0,  0],
        [62,  0,  0]],

       [[72,  0,  0],
        [72,  0,  0],
        [71,  0,  0],
        ...,
        [63,  0,  0],
        [62,  0,  0],
        [62,  0,  0]],

       [[72,  0,  0],
        [72,  0,  0],
        [71,  0,  0],
        ...,
        [63,  0,  0],
        [62,  0,  0],
        [62,  0,  0]],

       ...,

       [[ 6,  0,  1],
        [ 6,  0,  1],
        [ 6,  0,  1],
        ...,
        [ 6,  0,  1],
        [ 6,  0,  1],
        [ 6,  0,  1]],

       [[ 6,  0,  1],
        [ 6,  0,  1],
        [ 6,  0,  1],
        ...,
        [ 6,  0,  1],
        [ 6,  0,  1],
        [ 6,  0,  1]],

       [[ 6,  0,  1],
        [ 6,  0,  1],
        [ 6,  0,  1],
        ...,
        [ 6,  0,  1],
        [ 6,  0,  1],
        [ 6,  0,  1]]], dtype=uint8)

In [25]:
print(ret)

83.0


In [29]:
cv2.imshow("Thers_img1",thers1)
cv2.imshow("Thers_img2",thers2)
cv2.imshow("Thers_img3",thers3)
cv2.imshow("Thers_img4",thres4)
cv2.imshow("Thers_img5",thres5)
cv2.waitKey(0)
cv2.destroyAllWindows()

NameError: name 'thres1' is not defined